version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "testing like crazy!"
      - run: npm install
      - run: npm run test
  extra:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "hey this is the third job!"
workflows:
  version: 2
  publish:
    jobs:
      - build
      - extra
      - test:
        requires:
          - extra # extra need to succeed to run test job      
