version: 2
jobs:
  build-1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  build-2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double trouble"
  workflows:
    version: 2
      wf-1:
        jobs:
          - build-1
          - build-2
